# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui_main.ui',
# licensing of '.\gui_main.ui' applies.
#
# Created: Mon Apr  6 18:26:42 2020
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(743, 810)
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(59, 59, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(59, 59, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(59, 59, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(59, 59, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(9)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/spotify/resources/icons/cuffie.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_Folder = QtWidgets.QFrame(self.centralwidget)
        self.frame_Folder.setMinimumSize(QtCore.QSize(0, 190))
        self.frame_Folder.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_Folder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Folder.setLineWidth(5)
        self.frame_Folder.setObjectName("frame_Folder")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_Folder)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_DownloadFolder = QtWidgets.QLabel(self.frame_Folder)
        self.label_DownloadFolder.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_DownloadFolder.setFont(font)
        self.label_DownloadFolder.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_DownloadFolder.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DownloadFolder.setObjectName("label_DownloadFolder")
        self.verticalLayout_2.addWidget(self.label_DownloadFolder)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.pushButtonFolder = QtWidgets.QPushButton(self.frame_Folder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonFolder.sizePolicy().hasHeightForWidth())
        self.pushButtonFolder.setSizePolicy(sizePolicy)
        self.pushButtonFolder.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonFolder.setFont(font)
        self.pushButtonFolder.setStyleSheet("background-color: rgb(253, 253, 253);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonFolder.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/spotify/resources/icons/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonFolder.setIcon(icon1)
        self.pushButtonFolder.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonFolder.setFlat(True)
        self.pushButtonFolder.setObjectName("pushButtonFolder")
        self.verticalLayout_2.addWidget(self.pushButtonFolder)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.plainTextDirectory = QtWidgets.QPlainTextEdit(self.frame_Folder)
        self.plainTextDirectory.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextDirectory.sizePolicy().hasHeightForWidth())
        self.plainTextDirectory.setSizePolicy(sizePolicy)
        self.plainTextDirectory.setMinimumSize(QtCore.QSize(200, 30))
        self.plainTextDirectory.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.plainTextDirectory.setFont(font)
        self.plainTextDirectory.setFrameShape(QtWidgets.QFrame.Box)
        self.plainTextDirectory.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plainTextDirectory.setReadOnly(True)
        self.plainTextDirectory.setObjectName("plainTextDirectory")
        self.verticalLayout_2.addWidget(self.plainTextDirectory)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addWidget(self.frame_Folder)
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem2)
        self.label_URL = QtWidgets.QLabel(self.centralwidget)
        self.label_URL.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(True)
        self.label_URL.setFont(font)
        self.label_URL.setAlignment(QtCore.Qt.AlignCenter)
        self.label_URL.setObjectName("label_URL")
        self.verticalLayout_3.addWidget(self.label_URL)
        self.plainTextEditUrl = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEditUrl.sizePolicy().hasHeightForWidth())
        self.plainTextEditUrl.setSizePolicy(sizePolicy)
        self.plainTextEditUrl.setMinimumSize(QtCore.QSize(0, 35))
        self.plainTextEditUrl.setMaximumSize(QtCore.QSize(16777215, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.plainTextEditUrl.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.plainTextEditUrl.setFont(font)
        self.plainTextEditUrl.setAutoFillBackground(True)
        self.plainTextEditUrl.setStyleSheet("background-color: rgb(229, 229, 229);")
        self.plainTextEditUrl.setFrameShape(QtWidgets.QFrame.Box)
        self.plainTextEditUrl.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plainTextEditUrl.setLineWidth(2)
        self.plainTextEditUrl.setDocumentTitle("")
        self.plainTextEditUrl.setPlainText("")
        self.plainTextEditUrl.setOverwriteMode(False)
        self.plainTextEditUrl.setBackgroundVisible(False)
        self.plainTextEditUrl.setCenterOnScroll(False)
        self.plainTextEditUrl.setObjectName("plainTextEditUrl")
        self.verticalLayout_3.addWidget(self.plainTextEditUrl)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.listWidgetUrls = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetUrls.sizePolicy().hasHeightForWidth())
        self.listWidgetUrls.setSizePolicy(sizePolicy)
        self.listWidgetUrls.setMinimumSize(QtCore.QSize(350, 0))
        self.listWidgetUrls.setMaximumSize(QtCore.QSize(16777215, 200))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.listWidgetUrls.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(11)
        font.setItalic(True)
        self.listWidgetUrls.setFont(font)
        self.listWidgetUrls.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.listWidgetUrls.setAlternatingRowColors(True)
        self.listWidgetUrls.setTextElideMode(QtCore.Qt.ElideRight)
        self.listWidgetUrls.setResizeMode(QtWidgets.QListView.Adjust)
        self.listWidgetUrls.setObjectName("listWidgetUrls")
        self.verticalLayout_3.addWidget(self.listWidgetUrls)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.StartPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartPushButton.setMinimumSize(QtCore.QSize(0, 100))
        self.StartPushButton.setMaximumSize(QtCore.QSize(1500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.StartPushButton.setFont(font)
        self.StartPushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.StartPushButton.setStyleSheet("background-color: rgb(76, 76, 76);\n"
"color: rgb(255, 255, 255);")
        self.StartPushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/spotify/resources/icons/down_music_red.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StartPushButton.setIcon(icon2)
        self.StartPushButton.setIconSize(QtCore.QSize(80, 80))
        self.StartPushButton.setAutoRepeat(True)
        self.StartPushButton.setFlat(True)
        self.StartPushButton.setObjectName("StartPushButton")
        self.verticalLayout_3.addWidget(self.StartPushButton)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        spacerItem6 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_bottomPhrase = QtWidgets.QLabel(self.centralwidget)
        self.label_bottomPhrase.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(14)
        self.label_bottomPhrase.setFont(font)
        self.label_bottomPhrase.setObjectName("label_bottomPhrase")
        self.horizontalLayout.addWidget(self.label_bottomPhrase)
        self.label_IconPlay = QtWidgets.QLabel(self.centralwidget)
        self.label_IconPlay.setMaximumSize(QtCore.QSize(40, 40))
        self.label_IconPlay.setText("")
        self.label_IconPlay.setPixmap(QtGui.QPixmap(":/spotify/resources/icons/play1.png"))
        self.label_IconPlay.setScaledContents(True)
        self.label_IconPlay.setObjectName("label_IconPlay")
        self.horizontalLayout.addWidget(self.label_IconPlay)
        self.label_IconHead = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_IconHead.sizePolicy().hasHeightForWidth())
        self.label_IconHead.setSizePolicy(sizePolicy)
        self.label_IconHead.setMaximumSize(QtCore.QSize(50, 50))
        self.label_IconHead.setText("")
        self.label_IconHead.setPixmap(QtGui.QPixmap(":/spotify/resources/icons/music4.png"))
        self.label_IconHead.setScaledContents(True)
        self.label_IconHead.setObjectName("label_IconHead")
        self.horizontalLayout.addWidget(self.label_IconHead)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 743, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuLanguage = QtWidgets.QMenu(self.menubar)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/spotify/resources/icons/language.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuLanguage.setIcon(icon3)
        self.menuLanguage.setObjectName("menuLanguage")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionhelp = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/spotify/resources/icons/interrogativo1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionhelp.setIcon(icon4)
        self.actionhelp.setObjectName("actionhelp")
        self.actionReadMe = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/spotify/resources/icons/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReadMe.setIcon(icon5)
        self.actionReadMe.setObjectName("actionReadMe")
        self.actionAdvanced = QtWidgets.QAction(MainWindow)
        self.actionAdvanced.setObjectName("actionAdvanced")
        self.actionL = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/spotify/resources/icons/ita.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionL.setIcon(icon6)
        self.actionL.setObjectName("actionL")
        self.actionEng = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/spotify/resources/icons/eng.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEng.setIcon(icon7)
        self.actionEng.setObjectName("actionEng")
        self.actionFormat = QtWidgets.QAction(MainWindow)
        self.actionFormat.setObjectName("actionFormat")
        self.actionOverride_Policy = QtWidgets.QAction(MainWindow)
        self.actionOverride_Policy.setObjectName("actionOverride_Policy")
        self.menuMenu.addAction(self.actionAdvanced)
        self.menuMenu.addAction(self.actionFormat)
        self.menuMenu.addAction(self.actionOverride_Policy)
        self.menuHelp.addAction(self.actionhelp)
        self.menuHelp.addAction(self.actionReadMe)
        self.menuLanguage.addAction(self.actionL)
        self.menuLanguage.addAction(self.actionEng)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuLanguage.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MyTuneFy", None, -1))
        self.label_DownloadFolder.setText(QtWidgets.QApplication.translate("MainWindow", "Download Folder", None, -1))
        self.plainTextDirectory.setWhatsThis(QtWidgets.QApplication.translate("MainWindow", "Download folder", None, -1))
        self.plainTextDirectory.setPlainText(QtWidgets.QApplication.translate("MainWindow", "C:\\Music", None, -1))
        self.label_URL.setText(QtWidgets.QApplication.translate("MainWindow", "URL", None, -1))
        self.StartPushButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "download", None, -1))
        self.label_bottomPhrase.setText(QtWidgets.QApplication.translate("MainWindow", "Where words fail, music speaks.", None, -1))
        self.menuMenu.setTitle(QtWidgets.QApplication.translate("MainWindow", "Menu", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.menuLanguage.setTitle(QtWidgets.QApplication.translate("MainWindow", "Language", None, -1))
        self.actionhelp.setText(QtWidgets.QApplication.translate("MainWindow", "Manual", None, -1))
        self.actionReadMe.setText(QtWidgets.QApplication.translate("MainWindow", "ReadMe", None, -1))
        self.actionAdvanced.setText(QtWidgets.QApplication.translate("MainWindow", "Advanced", None, -1))
        self.actionL.setText(QtWidgets.QApplication.translate("MainWindow", "Ita", None, -1))
        self.actionEng.setText(QtWidgets.QApplication.translate("MainWindow", "Eng", None, -1))
        self.actionFormat.setText(QtWidgets.QApplication.translate("MainWindow", "Format", None, -1))
        self.actionOverride_Policy.setText(QtWidgets.QApplication.translate("MainWindow", "Override Policy", None, -1))

from .import icon_rc
