# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui_main_player.ui',
# licensing of '.\gui_main_player.ui' applies.
#
# Created: Sat Apr 18 01:53:08 2020
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_PlayerMainWindow(object):
    def setupUi(self, PlayerMainWindow):
        PlayerMainWindow.setObjectName("PlayerMainWindow")
        PlayerMainWindow.resize(992, 883)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        PlayerMainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/spotify/resources/icons/play1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PlayerMainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(PlayerMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_user = QtWidgets.QLabel(self.frame_4)
        self.label_user.setMinimumSize(QtCore.QSize(150, 0))
        self.label_user.setMaximumSize(QtCore.QSize(16777215, 200))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_user.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_user.setFont(font)
        self.label_user.setAlignment(QtCore.Qt.AlignCenter)
        self.label_user.setObjectName("label_user")
        self.horizontalLayout_2.addWidget(self.label_user)
        self.textEditSearch = QtWidgets.QTextEdit(self.frame_4)
        self.textEditSearch.setMinimumSize(QtCore.QSize(150, 30))
        self.textEditSearch.setMaximumSize(QtCore.QSize(200, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.textEditSearch.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEditSearch.setFont(font)
        self.textEditSearch.setStyleSheet("")
        self.textEditSearch.setOverwriteMode(True)
        self.textEditSearch.setObjectName("textEditSearch")
        self.horizontalLayout_2.addWidget(self.textEditSearch)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frameTop = QtWidgets.QFrame(self.centralwidget)
        self.frameTop.setMinimumSize(QtCore.QSize(0, 110))
        self.frameTop.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frameTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTop.setObjectName("frameTop")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frameTop)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.TopLayout = QtWidgets.QHBoxLayout()
        self.TopLayout.setContentsMargins(10, 10, 10, 10)
        self.TopLayout.setObjectName("TopLayout")
        self.frame = QtWidgets.QFrame(self.frameTop)
        self.frame.setMinimumSize(QtCore.QSize(80, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 40)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toolButtonGeneral = QtWidgets.QToolButton(self.frame)
        self.toolButtonGeneral.setMinimumSize(QtCore.QSize(60, 30))
        self.toolButtonGeneral.setMaximumSize(QtCore.QSize(75, 60))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(8, 8, 8))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 8, 8))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 8, 8))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 8, 8))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 8, 8))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 8, 8))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 8, 8))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 8, 8))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 8, 8))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.toolButtonGeneral.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.toolButtonGeneral.setFont(font)
        self.toolButtonGeneral.setStyleSheet("background-color: rgb(8, 8, 8);\n"
"border-radius: 5px;")
        self.toolButtonGeneral.setIconSize(QtCore.QSize(20, 20))
        self.toolButtonGeneral.setObjectName("toolButtonGeneral")
        self.verticalLayout_4.addWidget(self.toolButtonGeneral)
        self.TopLayout.addWidget(self.frame)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.TopLayout.addItem(spacerItem)
        self.comboBoxCategory = QtWidgets.QComboBox(self.frameTop)
        self.comboBoxCategory.setMinimumSize(QtCore.QSize(150, 30))
        self.comboBoxCategory.setMaximumSize(QtCore.QSize(250, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(2, 2, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(2, 2, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.comboBoxCategory.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxCategory.setFont(font)
        self.comboBoxCategory.setStyleSheet("")
        self.comboBoxCategory.setObjectName("comboBoxCategory")
        self.comboBoxCategory.addItem("")
        self.comboBoxCategory.addItem("")
        self.comboBoxCategory.addItem("")
        self.comboBoxCategory.addItem("")
        self.TopLayout.addWidget(self.comboBoxCategory)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.TopLayout.addItem(spacerItem1)
        self.StreamModeButton = QtWidgets.QPushButton(self.frameTop)
        self.StreamModeButton.setMinimumSize(QtCore.QSize(144, 35))
        self.StreamModeButton.setMaximumSize(QtCore.QSize(160, 80))
        palette = QtGui.QPalette()
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 226, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 167, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 226, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 167, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 226, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 167, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 226, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 167, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 226, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 167, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 226, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 167, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 226, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 167, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 226, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 167, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 226, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 167, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.StreamModeButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.StreamModeButton.setFont(font)
        self.StreamModeButton.setStyleSheet("QPushButton {\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 30px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #00e200, stop: 1 #00a700);\n"
"    min-width: 140px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/spotify/resources/icons/stream_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StreamModeButton.setIcon(icon1)
        self.StreamModeButton.setDefault(False)
        self.StreamModeButton.setObjectName("StreamModeButton")
        self.TopLayout.addWidget(self.StreamModeButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.TopLayout.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.frameTop)
        self.label_2.setMinimumSize(QtCore.QSize(185, 0))
        self.label_2.setMaximumSize(QtCore.QSize(180, 90))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.TopLayout.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.TopLayout.addItem(spacerItem3)
        self.Folder = QtWidgets.QPushButton(self.frameTop)
        self.Folder.setObjectName("Folder")
        self.TopLayout.addWidget(self.Folder)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.TopLayout.addItem(spacerItem4)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frameTop)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.TopLayout.addWidget(self.plainTextEdit)
        self.horizontalLayout_7.addLayout(self.TopLayout)
        self.verticalLayout_2.addWidget(self.frameTop)
        self.centralhorizontalLayout = QtWidgets.QHBoxLayout()
        self.centralhorizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.centralhorizontalLayout.setObjectName("centralhorizontalLayout")
        self.verticalLayout_Library = QtWidgets.QVBoxLayout()
        self.verticalLayout_Library.setContentsMargins(0, 10, 10, 10)
        self.verticalLayout_Library.setObjectName("verticalLayout_Library")
        self.label_library = QtWidgets.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(203, 203, 203))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 203, 203))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_library.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_library.setFont(font)
        self.label_library.setAlignment(QtCore.Qt.AlignCenter)
        self.label_library.setObjectName("label_library")
        self.verticalLayout_Library.addWidget(self.label_library)
        self.horizontalLayout_library = QtWidgets.QHBoxLayout()
        self.horizontalLayout_library.setContentsMargins(10, 5, -1, -1)
        self.horizontalLayout_library.setObjectName("horizontalLayout_library")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setAutoFillBackground(False)
        self.listWidget.setStyleSheet("QListView {\n"
"background-color: rgb(30, 30, 30);\n"
"}")
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_library.addWidget(self.listWidget)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setMinimumSize(QtCore.QSize(20, 390))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalLayout_library.addWidget(self.verticalScrollBar)
        self.verticalLayout_Library.addLayout(self.horizontalLayout_library)
        self.newPlaylistButton = QtWidgets.QPushButton(self.centralwidget)
        self.newPlaylistButton.setEnabled(False)
        self.newPlaylistButton.setObjectName("newPlaylistButton")
        self.verticalLayout_Library.addWidget(self.newPlaylistButton)
        self.centralhorizontalLayout.addLayout(self.verticalLayout_Library)
        self.frame_songs = QtWidgets.QFrame(self.centralwidget)
        self.frame_songs.setMinimumSize(QtCore.QSize(0, 450))
        self.frame_songs.setStyleSheet("background-color: rgb(25, 25, 25);")
        self.frame_songs.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_songs.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_songs.setObjectName("frame_songs")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_songs)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.playlist_label = QtWidgets.QLabel(self.frame_songs)
        self.playlist_label.setMinimumSize(QtCore.QSize(450, 35))
        self.playlist_label.setMaximumSize(QtCore.QSize(350, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.playlist_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.playlist_label.setFont(font)
        self.playlist_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.playlist_label.setObjectName("playlist_label")
        self.horizontalLayout.addWidget(self.playlist_label)
        self.pushButtonPlaylist = QtWidgets.QPushButton(self.frame_songs)
        self.pushButtonPlaylist.setMinimumSize(QtCore.QSize(84, 30))
        self.pushButtonPlaylist.setMaximumSize(QtCore.QSize(180, 55))
        palette = QtGui.QPalette()
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 226, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 167, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 226, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 167, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 226, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 167, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 226, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 167, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 226, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 167, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 226, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 167, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 226, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 167, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 226, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 167, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 226, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 167, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButtonPlaylist.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.pushButtonPlaylist.setFont(font)
        self.pushButtonPlaylist.setStyleSheet("QPushButton {\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 15px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #00e200, stop: 1 #00a700);\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"        background: qlineargradient(x1 : 0, y1 : 0, x2 : 0, y2 :   1, stop :   0.0 #ffd9aa,\n"
"                stop :   0.5 #ffbb6e, stop :   0.55 #feae42, stop :   1.0 #fedb74);\n"
"        color: black\n"
"}\n"
"")
        self.pushButtonPlaylist.setObjectName("pushButtonPlaylist")
        self.horizontalLayout.addWidget(self.pushButtonPlaylist)
        self.toolButtonPlaylist = QtWidgets.QToolButton(self.frame_songs)
        self.toolButtonPlaylist.setMinimumSize(QtCore.QSize(45, 30))
        self.toolButtonPlaylist.setObjectName("toolButtonPlaylist")
        self.horizontalLayout.addWidget(self.toolButtonPlaylist)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.title_label = QtWidgets.QLabel(self.frame_songs)
        self.title_label.setMinimumSize(QtCore.QSize(350, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.title_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.horizontalLayout_3.addWidget(self.title_label)
        self.artist_label = QtWidgets.QLabel(self.frame_songs)
        self.artist_label.setMinimumSize(QtCore.QSize(300, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.artist_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.artist_label.setFont(font)
        self.artist_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.artist_label.setAlignment(QtCore.Qt.AlignCenter)
        self.artist_label.setObjectName("artist_label")
        self.horizontalLayout_3.addWidget(self.artist_label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableView = QtWidgets.QTableView(self.frame_songs)
        self.tableView.setStyleSheet("QTableView{\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: white\n"
"}\n"
"")
        self.tableView.setShowGrid(False)
        self.tableView.setGridStyle(QtCore.Qt.NoPen)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_6.addWidget(self.tableView)
        self.verticalLayout.addLayout(self.verticalLayout_6)
        self.centralhorizontalLayout.addWidget(self.frame_songs)
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar_2.setCursor(QtCore.Qt.ArrowCursor)
        self.verticalScrollBar_2.setStyleSheet("color: rgb(70, 70, 70);\n"
"border-color: rgb(74, 74, 74);\n"
"background-color: rgb(81, 81, 81);")
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.centralhorizontalLayout.addWidget(self.verticalScrollBar_2)
        self.verticalLayout_2.addLayout(self.centralhorizontalLayout)
        self.frame_bottom = QtWidgets.QFrame(self.centralwidget)
        self.frame_bottom.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_bottom.setMaximumSize(QtCore.QSize(16777215, 115))
        self.frame_bottom.setStyleSheet("background-color: rgb(40, 40, 40);")
        self.frame_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bottom.setObjectName("frame_bottom")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_bottom)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.bottomLayout = QtWidgets.QHBoxLayout()
        self.bottomLayout.setContentsMargins(10, 0, 1, 0)
        self.bottomLayout.setObjectName("bottomLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_bottom)
        self.frame_3.setMinimumSize(QtCore.QSize(260, 80))
        self.frame_3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.song_name_label = QtWidgets.QLabel(self.frame_3)
        self.song_name_label.setMaximumSize(QtCore.QSize(350, 350))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.song_name_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.song_name_label.setFont(font)
        self.song_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.song_name_label.setObjectName("song_name_label")
        self.verticalLayout_5.addWidget(self.song_name_label)
        self.song_artist_label = QtWidgets.QLabel(self.frame_3)
        self.song_artist_label.setMaximumSize(QtCore.QSize(300, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.song_artist_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.song_artist_label.setFont(font)
        self.song_artist_label.setAlignment(QtCore.Qt.AlignCenter)
        self.song_artist_label.setObjectName("song_artist_label")
        self.verticalLayout_5.addWidget(self.song_artist_label)
        self.bottomLayout.addWidget(self.frame_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottomLayout.addItem(spacerItem5)
        self.frame_control = QtWidgets.QFrame(self.frame_bottom)
        self.frame_control.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_control.setMaximumSize(QtCore.QSize(16777215, 115))
        self.frame_control.setStyleSheet("")
        self.frame_control.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_control.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_control.setObjectName("frame_control")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_control)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(65, -1, 65, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.shuffleButton = QtWidgets.QPushButton(self.frame_control)
        self.shuffleButton.setMinimumSize(QtCore.QSize(0, 35))
        self.shuffleButton.setStyleSheet("QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}")
        self.shuffleButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/spotify/resources/icons/shuffle1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shuffleButton.setIcon(icon2)
        self.shuffleButton.setIconSize(QtCore.QSize(25, 18))
        self.shuffleButton.setCheckable(True)
        self.shuffleButton.setFlat(True)
        self.shuffleButton.setObjectName("shuffleButton")
        self.horizontalLayout_4.addWidget(self.shuffleButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.backTrackButton = QtWidgets.QPushButton(self.frame_control)
        self.backTrackButton.setMinimumSize(QtCore.QSize(60, 60))
        self.backTrackButton.setMaximumSize(QtCore.QSize(65, 65))
        self.backTrackButton.setAutoFillBackground(False)
        self.backTrackButton.setStyleSheet("QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}")
        self.backTrackButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/spotify/resources/icons/backtrack3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backTrackButton.setIcon(icon3)
        self.backTrackButton.setIconSize(QtCore.QSize(30, 30))
        self.backTrackButton.setCheckable(True)
        self.backTrackButton.setFlat(True)
        self.backTrackButton.setObjectName("backTrackButton")
        self.horizontalLayout_4.addWidget(self.backTrackButton)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.PlayPauseButton = QtWidgets.QPushButton(self.frame_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlayPauseButton.sizePolicy().hasHeightForWidth())
        self.PlayPauseButton.setSizePolicy(sizePolicy)
        self.PlayPauseButton.setMinimumSize(QtCore.QSize(35, 35))
        self.PlayPauseButton.setMaximumSize(QtCore.QSize(60, 30))
        self.PlayPauseButton.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(40, 40, 40);\n"
"    image: url(:/spotify/resources/icons/play-red.png);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    image: url(:/spotify/resources/icons/pause-butt.png);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}")
        self.PlayPauseButton.setText("")
        self.PlayPauseButton.setIconSize(QtCore.QSize(35, 35))
        self.PlayPauseButton.setCheckable(False)
        self.PlayPauseButton.setChecked(False)
        self.PlayPauseButton.setAutoExclusive(False)
        self.PlayPauseButton.setFlat(True)
        self.PlayPauseButton.setObjectName("PlayPauseButton")
        self.horizontalLayout_4.addWidget(self.PlayPauseButton)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.nextTrackButton = QtWidgets.QPushButton(self.frame_control)
        self.nextTrackButton.setMinimumSize(QtCore.QSize(0, 45))
        self.nextTrackButton.setStyleSheet("QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}")
        self.nextTrackButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/spotify/resources/icons/next3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextTrackButton.setIcon(icon4)
        self.nextTrackButton.setIconSize(QtCore.QSize(30, 30))
        self.nextTrackButton.setCheckable(True)
        self.nextTrackButton.setFlat(True)
        self.nextTrackButton.setObjectName("nextTrackButton")
        self.horizontalLayout_4.addWidget(self.nextTrackButton)
        spacerItem9 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.repeatButton = QtWidgets.QPushButton(self.frame_control)
        self.repeatButton.setMinimumSize(QtCore.QSize(55, 40))
        self.repeatButton.setMaximumSize(QtCore.QSize(65, 60))
        self.repeatButton.setAutoFillBackground(False)
        self.repeatButton.setStyleSheet("QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}")
        self.repeatButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/spotify/resources/icons/repeat-track.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.repeatButton.setIcon(icon5)
        self.repeatButton.setIconSize(QtCore.QSize(25, 20))
        self.repeatButton.setCheckable(True)
        self.repeatButton.setFlat(True)
        self.repeatButton.setObjectName("repeatButton")
        self.horizontalLayout_4.addWidget(self.repeatButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalSlider = QtWidgets.QSlider(self.frame_control)
        self.horizontalSlider.setMinimumSize(QtCore.QSize(0, 15))
        self.horizontalSlider.setMaximumSize(QtCore.QSize(16777215, 15))
        self.horizontalSlider.setStyleSheet("")
        self.horizontalSlider.setSliderPosition(0)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_3.addWidget(self.horizontalSlider)
        self.bottomLayout.addWidget(self.frame_control)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottomLayout.addItem(spacerItem11)
        self.frame_2 = QtWidgets.QFrame(self.frame_bottom)
        self.frame_2.setMinimumSize(QtCore.QSize(125, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_2.setStyleSheet("background-color: rgb(203, 203, 203);\n"
"background-color: rgb(40, 40, 40);\n"
"background-image: url(:/spotify/resources/icons/play-red.png);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.IconLogo = QtWidgets.QLabel(self.frame_2)
        self.IconLogo.setMaximumSize(QtCore.QSize(60, 60))
        self.IconLogo.setText("")
        self.IconLogo.setPixmap(QtGui.QPixmap(":/spotify/resources/icons/cuffie2.png"))
        self.IconLogo.setScaledContents(True)
        self.IconLogo.setObjectName("IconLogo")
        self.horizontalLayout_5.addWidget(self.IconLogo)
        self.verticalSlider = QtWidgets.QSlider(self.frame_2)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.horizontalLayout_5.addWidget(self.verticalSlider)
        self.bottomLayout.addWidget(self.frame_2)
        self.horizontalLayout_6.addLayout(self.bottomLayout)
        self.verticalLayout_2.addWidget(self.frame_bottom)
        PlayerMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PlayerMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 992, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        PlayerMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PlayerMainWindow)
        self.statusbar.setObjectName("statusbar")
        PlayerMainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(PlayerMainWindow)
        QtCore.QMetaObject.connectSlotsByName(PlayerMainWindow)

    def retranslateUi(self, PlayerMainWindow):
        PlayerMainWindow.setWindowTitle(QtWidgets.QApplication.translate("PlayerMainWindow", "MyTuneFy Player", None, -1))
        self.label_user.setText(QtWidgets.QApplication.translate("PlayerMainWindow", "USER", None, -1))
        self.textEditSearch.setHtml(QtWidgets.QApplication.translate("PlayerMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Gill Sans MT\';\">Cerca</span></p></body></html>", None, -1))
        self.toolButtonGeneral.setText(QtWidgets.QApplication.translate("PlayerMainWindow", "...", None, -1))
        self.comboBoxCategory.setCurrentText(QtWidgets.QApplication.translate("PlayerMainWindow", "Playlist", None, -1))
        self.comboBoxCategory.setItemText(0, QtWidgets.QApplication.translate("PlayerMainWindow", "Playlist", None, -1))
        self.comboBoxCategory.setItemText(1, QtWidgets.QApplication.translate("PlayerMainWindow", "Album", None, -1))
        self.comboBoxCategory.setItemText(2, QtWidgets.QApplication.translate("PlayerMainWindow", "Artista", None, -1))
        self.comboBoxCategory.setItemText(3, QtWidgets.QApplication.translate("PlayerMainWindow", "Brani", None, -1))
        self.StreamModeButton.setText(QtWidgets.QApplication.translate("PlayerMainWindow", "Stream ", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("PlayerMainWindow", "OFFLINE", None, -1))
        self.Folder.setText(QtWidgets.QApplication.translate("PlayerMainWindow", "PushButton", None, -1))
        self.label_library.setText(QtWidgets.QApplication.translate("PlayerMainWindow", "La Tua Libreria", None, -1))
        self.newPlaylistButton.setText(QtWidgets.QApplication.translate("PlayerMainWindow", "Nuova Playlist", None, -1))
        self.playlist_label.setText(QtWidgets.QApplication.translate("PlayerMainWindow", "Playlist name", None, -1))
        self.pushButtonPlaylist.setText(QtWidgets.QApplication.translate("PlayerMainWindow", "Play", None, -1))
        self.toolButtonPlaylist.setText(QtWidgets.QApplication.translate("PlayerMainWindow", "...", None, -1))
        self.title_label.setText(QtWidgets.QApplication.translate("PlayerMainWindow", "TITOLO", None, -1))
        self.artist_label.setText(QtWidgets.QApplication.translate("PlayerMainWindow", "ARTISTA", None, -1))
        self.song_name_label.setText(QtWidgets.QApplication.translate("PlayerMainWindow", "SONG NAME", None, -1))
        self.song_artist_label.setText(QtWidgets.QApplication.translate("PlayerMainWindow", "Artist", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("PlayerMainWindow", "File", None, -1))
        self.menuEdit.setTitle(QtWidgets.QApplication.translate("PlayerMainWindow", "Edit", None, -1))

from .import icon_rc

